version: '3.8'

services:
  codebox:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    user: root  # Added to run as root